package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.47

import (
	"context"

	"github.com/studded/events-graph-api/graph/model"
)

// User is the resolver for the user field.
func (r *roleResolver) User(ctx context.Context, obj *model.Role) (*model.User, error) {
	return r.UsersRepo.GetUserByID(obj.UserID)
}

// Event is the resolver for the event field.
func (r *roleResolver) Event(ctx context.Context, obj *model.Role) (*model.Event, error) {
	return r.EventsRepo.GetEventByID(obj.EventID)
}

// Role returns RoleResolver implementation.
func (r *Resolver) Role() RoleResolver { return &roleResolver{r} }

type roleResolver struct{ *Resolver }
